kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:31270"]
    endpoint = ["http://localhost:31270"]
nodes:
- role: control-plane
